const BuffType = {
    INTERNAL: 1,
    AURA: 2,
    COMBAT_ENCHANCER: 3,
    COMBAT_DEHANCER: 4,
    SPELL_SHIELD: 5,
    STUN: 6,
    INVISIBILITY: 7,
    SILENCE: 8,
    TAUNT: 9,
    POLYMORPH: 10,
    SLOW: 11,
    SNARE: 12,
    DAMAGE: 13,
    HEAL: 14,
    HASTE: 15,
    SPELL_IMMUNITY: 16,
    PHYSICAL_IMMUNITY: 17,
    INVULNERABILITY: 18,
    SLEEP: 19,
    NEAR_SIGHT: 20,
    FRENZY: 21,
    FEAR: 22,
    CHARM: 23,
    POISON: 24,
    SUPPRESSION: 25,
    BLIND: 26,
    COUNTER: 27,
    SHRED: 28,
    FLEE: 29,
    KNOCKUP: 30,
    KNOCKBACK: 31,
    DISARM: 32,
};

Object.freeze(BuffType);
export default BuffType;
