const MoveOrder = {
    MOVE_ORDER_ATTACKMOVE: 1,
    MOVE_ORDER_ATTACKTERRAIN_ONCE: 2,
    MOVE_ORDER_ATTACKTERRAIN_SUSTAINED: 3,
    MOVE_ORDER_ATTACKTO: 4,
    MOVE_ORDER_HOLD: 5,
    MOVE_ORDER_MOVETO: 6,
    MOVE_ORDER_PETHARDATTACK: 7,
    MOVE_ORDER_PETHARDMOVE: 8,
    MOVE_ORDER_PETHARDRETURN: 9,
    MOVE_ORDER_PETHARDSTOP: 10,
    MOVE_ORDER_STOP: 11,
    MOVE_ORDER_TAUNT: 12,
};

Object.freeze(MoveOrder);
export default MoveOrder;
